"""initial schema

Revision ID: 5c1dd4a2c324
Revises: 
Create Date: 2026-09-09 09:58:34.600989
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5c1dd4a2c324'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('plan', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenants_slug'))
    )
    op.create_table('audit_logs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_email', sa.String(length=200), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=60), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_audit_logs_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_company_id'), 'audit_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('companies',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fy_start_month', sa.Integer(), nullable=False),
    sa.Column('allow_negative_stock', sa.Boolean(), nullable=False),
    sa.Column('default_wastage_pct', sa.Numeric(precision=7, scale=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_companies_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_index(op.f('ix_companies_tenant_id'), 'companies', ['tenant_id'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_roles_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('tenant_id', 'name', name=op.f('uq_roles_tenant_id_name'))
    )
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_table('sync_outbox',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('op_id', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('operation', sa.String(length=30), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_sync_outbox_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_outbox')),
    sa.UniqueConstraint('tenant_id', 'device_id', 'op_id', name=op.f('uq_sync_outbox_tenant_id_device_id_op_id'))
    )
    op.create_index(op.f('ix_sync_outbox_company_id'), 'sync_outbox', ['company_id'], unique=False)
    op.create_index(op.f('ix_sync_outbox_tenant_id'), 'sync_outbox', ['tenant_id'], unique=False)
    op.create_table('account_groups',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('nature', sa.String(length=20), nullable=False),
    sa.Column('report', sa.String(length=20), nullable=False),
    sa.Column('affects_gross_profit', sa.Boolean(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_account_groups_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['account_groups.id'], name=op.f('fk_account_groups_parent_id_account_groups')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_account_groups_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_groups')),
    sa.UniqueConstraint('company_id', 'code', name=op.f('uq_account_groups_company_id_code'))
    )
    op.create_index(op.f('ix_account_groups_company_id'), 'account_groups', ['company_id'], unique=False)
    op.create_index(op.f('ix_account_groups_tenant_id'), 'account_groups', ['tenant_id'], unique=False)
    op.create_table('branches',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_branches_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_branches_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches')),
    sa.UniqueConstraint('company_id', 'code', name=op.f('uq_branches_company_id_code'))
    )
    op.create_index(op.f('ix_branches_company_id'), 'branches', ['company_id'], unique=False)
    op.create_index(op.f('ix_branches_tenant_id'), 'branches', ['tenant_id'], unique=False)
    op.create_table('brands',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_brands_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_brands_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands')),
    sa.UniqueConstraint('company_id', 'name', name=op.f('uq_brands_company_id_name'))
    )
    op.create_index(op.f('ix_brands_company_id'), 'brands', ['company_id'], unique=False)
    op.create_index(op.f('ix_brands_tenant_id'), 'brands', ['tenant_id'], unique=False)
    op.create_table('categories',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_categories_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_categories_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('company_id', 'name', name=op.f('uq_categories_company_id_name'))
    )
    op.create_index(op.f('ix_categories_company_id'), 'categories', ['company_id'], unique=False)
    op.create_index(op.f('ix_categories_tenant_id'), 'categories', ['tenant_id'], unique=False)
    op.create_table('fiscal_years',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('locked_till', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_fiscal_years_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_fiscal_years_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fiscal_years')),
    sa.UniqueConstraint('company_id', 'name', name=op.f('uq_fiscal_years_company_id_name'))
    )
    op.create_index(op.f('ix_fiscal_years_company_id'), 'fiscal_years', ['company_id'], unique=False)
    op.create_index(op.f('ix_fiscal_years_tenant_id'), 'fiscal_years', ['tenant_id'], unique=False)
    op.create_table('parties',
    sa.Column('party_type', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('whatsapp', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('shipping_address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit_days', sa.Integer(), nullable=False),
    sa.Column('price_tier', sa.String(length=20), nullable=False),
    sa.Column('ledger_id', sa.UUID(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('whatsapp_opt_in', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_parties_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], name=op.f('fk_parties_ledger_id_ledgers'), use_alter=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_parties_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parties'))
    )
    op.create_index(op.f('ix_parties_company_id'), 'parties', ['company_id'], unique=False)
    op.create_index('ix_parties_company_name', 'parties', ['company_id', 'name'], unique=False)
    op.create_index(op.f('ix_parties_tenant_id'), 'parties', ['tenant_id'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_settings_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_settings_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings')),
    sa.UniqueConstraint('company_id', 'key', name=op.f('uq_settings_company_id_key'))
    )
    op.create_index(op.f('ix_settings_company_id'), 'settings', ['company_id'], unique=False)
    op.create_index(op.f('ix_settings_tenant_id'), 'settings', ['tenant_id'], unique=False)
    op.create_table('units',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_units_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_units_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_units')),
    sa.UniqueConstraint('company_id', 'symbol', name=op.f('uq_units_company_id_symbol'))
    )
    op.create_index(op.f('ix_units_company_id'), 'units', ['company_id'], unique=False)
    op.create_index(op.f('ix_units_tenant_id'), 'units', ['tenant_id'], unique=False)
    op.create_table('godowns',
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_godowns_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_godowns_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_godowns_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_godowns')),
    sa.UniqueConstraint('company_id', 'code', name=op.f('uq_godowns_company_id_code'))
    )
    op.create_index(op.f('ix_godowns_branch_id'), 'godowns', ['branch_id'], unique=False)
    op.create_index(op.f('ix_godowns_company_id'), 'godowns', ['company_id'], unique=False)
    op.create_index(op.f('ix_godowns_tenant_id'), 'godowns', ['tenant_id'], unique=False)
    op.create_table('ledgers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('opening_type', sa.String(length=2), nullable=False),
    sa.Column('system_key', sa.String(length=40), nullable=True),
    sa.Column('party_id', sa.UUID(), nullable=True),
    sa.Column('is_bank', sa.Boolean(), nullable=False),
    sa.Column('is_cash', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('bank_account_no', sa.String(length=40), nullable=True),
    sa.Column('bank_ifsc', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_ledgers_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['account_groups.id'], name=op.f('fk_ledgers_group_id_account_groups'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_ledgers_party_id_parties'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_ledgers_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledgers')),
    sa.UniqueConstraint('company_id', 'name', name=op.f('uq_ledgers_company_id_name'))
    )
    op.create_index(op.f('ix_ledgers_company_id'), 'ledgers', ['company_id'], unique=False)
    op.create_index('ix_ledgers_company_system_key', 'ledgers', ['company_id', 'system_key'], unique=False)
    op.create_index(op.f('ix_ledgers_group_id'), 'ledgers', ['group_id'], unique=False)
    op.create_index(op.f('ix_ledgers_tenant_id'), 'ledgers', ['tenant_id'], unique=False)
    op.create_table('number_sequences',
    sa.Column('doc_type', sa.String(length=40), nullable=False),
    sa.Column('fiscal_year_id', sa.UUID(), nullable=True),
    sa.Column('prefix', sa.String(length=30), nullable=False),
    sa.Column('next_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_number_sequences_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], name=op.f('fk_number_sequences_fiscal_year_id_fiscal_years'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_number_sequences_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_number_sequences')),
    sa.UniqueConstraint('company_id', 'doc_type', 'fiscal_year_id', name=op.f('uq_number_sequences_company_id_doc_type_fiscal_year_id'))
    )
    op.create_index(op.f('ix_number_sequences_company_id'), 'number_sequences', ['company_id'], unique=False)
    op.create_index(op.f('ix_number_sequences_fiscal_year_id'), 'number_sequences', ['fiscal_year_id'], unique=False)
    op.create_index(op.f('ix_number_sequences_tenant_id'), 'number_sequences', ['tenant_id'], unique=False)
    op.create_table('products',
    sa.Column('sku', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('product_type', sa.String(length=20), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('hsn_code', sa.String(length=10), nullable=True),
    sa.Column('gst_rate', sa.Numeric(precision=7, scale=3), nullable=False),
    sa.Column('barcode', sa.String(length=60), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stock_unit_id', sa.UUID(), nullable=False),
    sa.Column('pieces_per_box', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('sqft_per_box', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('sqm_per_box', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('boxes_per_pallet', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('weight_kg_per_box', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('series', sa.String(length=100), nullable=True),
    sa.Column('design', sa.String(length=100), nullable=True),
    sa.Column('colour', sa.String(length=60), nullable=True),
    sa.Column('size', sa.String(length=40), nullable=True),
    sa.Column('thickness_mm', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('finish', sa.String(length=60), nullable=True),
    sa.Column('material', sa.String(length=60), nullable=True),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('pattern', sa.String(length=60), nullable=True),
    sa.Column('application', sa.String(length=40), nullable=True),
    sa.Column('model_no', sa.String(length=60), nullable=True),
    sa.Column('warranty_months', sa.Integer(), nullable=True),
    sa.Column('installation_notes', sa.Text(), nullable=True),
    sa.Column('set_contents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('compatible_skus', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('retail_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('dealer_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('project_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('mrp', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=7, scale=3), nullable=False),
    sa.Column('reorder_level', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('track_batches', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_products_brand_id_brands'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_products_category_id_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_products_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_unit_id'], ['units.id'], name=op.f('fk_products_stock_unit_id_units'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_products_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('company_id', 'sku', name=op.f('uq_products_company_id_sku'))
    )
    op.create_index(op.f('ix_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_company_id'), 'products', ['company_id'], unique=False)
    op.create_index('ix_products_company_name', 'products', ['company_id', 'name'], unique=False)
    op.create_index(op.f('ix_products_stock_unit_id'), 'products', ['stock_unit_id'], unique=False)
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    op.create_table('projects',
    sa.Column('party_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('site_address', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('budget', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_projects_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_projects_party_id_parties'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_projects_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_company_id'), 'projects', ['company_id'], unique=False)
    op.create_index(op.f('ix_projects_party_id'), 'projects', ['party_id'], unique=False)
    op.create_index(op.f('ix_projects_tenant_id'), 'projects', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('default_company_id', sa.UUID(), nullable=True),
    sa.Column('default_branch_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['default_branch_id'], ['branches.id'], name=op.f('fk_users_default_branch_id_branches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['default_company_id'], ['companies.id'], name=op.f('fk_users_default_company_id_companies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('tenant_id', 'email', name=op.f('uq_users_tenant_id_email'))
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('vouchers',
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('fiscal_year_id', sa.UUID(), nullable=False),
    sa.Column('voucher_type', sa.String(length=30), nullable=False),
    sa.Column('voucher_no', sa.String(length=40), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('reference_type', sa.String(length=40), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('party_id', sa.UUID(), nullable=True),
    sa.Column('total_debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reverses_id', sa.UUID(), nullable=True),
    sa.Column('reversed_by_id', sa.UUID(), nullable=True),
    sa.Column('posted_by', sa.UUID(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_vouchers_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_vouchers_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], name=op.f('fk_vouchers_fiscal_year_id_fiscal_years'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_vouchers_party_id_parties'), use_alter=True),
    sa.ForeignKeyConstraint(['reversed_by_id'], ['vouchers.id'], name=op.f('fk_vouchers_reversed_by_id_vouchers')),
    sa.ForeignKeyConstraint(['reverses_id'], ['vouchers.id'], name=op.f('fk_vouchers_reverses_id_vouchers')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_vouchers_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vouchers')),
    sa.UniqueConstraint('company_id', 'idempotency_key', name=op.f('uq_vouchers_company_id_idempotency_key')),
    sa.UniqueConstraint('company_id', 'voucher_type', 'voucher_no', name=op.f('uq_vouchers_company_id_voucher_type_voucher_no'))
    )
    op.create_index(op.f('ix_vouchers_branch_id'), 'vouchers', ['branch_id'], unique=False)
    op.create_index(op.f('ix_vouchers_company_id'), 'vouchers', ['company_id'], unique=False)
    op.create_index(op.f('ix_vouchers_date'), 'vouchers', ['date'], unique=False)
    op.create_index(op.f('ix_vouchers_fiscal_year_id'), 'vouchers', ['fiscal_year_id'], unique=False)
    op.create_index(op.f('ix_vouchers_reference_id'), 'vouchers', ['reference_id'], unique=False)
    op.create_index(op.f('ix_vouchers_tenant_id'), 'vouchers', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_vouchers_voucher_type'), 'vouchers', ['voucher_type'], unique=False)
    op.create_table('whatsapp_messages',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('party_id', sa.UUID(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('template', sa.String(length=60), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('doc_type', sa.String(length=40), nullable=True),
    sa.Column('doc_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_ref', sa.String(length=120), nullable=True),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_whatsapp_messages_company_id_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_whatsapp_messages_party_id_parties'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_whatsapp_messages_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_whatsapp_messages'))
    )
    op.create_index(op.f('ix_whatsapp_messages_company_id'), 'whatsapp_messages', ['company_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_doc_id'), 'whatsapp_messages', ['doc_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_party_id'), 'whatsapp_messages', ['party_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_tenant_id'), 'whatsapp_messages', ['tenant_id'], unique=False)
    op.create_table('batches',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('batch_no', sa.String(length=60), nullable=False),
    sa.Column('shade', sa.String(length=30), nullable=True),
    sa.Column('calibre', sa.String(length=30), nullable=True),
    sa.Column('mfg_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_batches_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_batches_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_batches_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batches')),
    sa.UniqueConstraint('product_id', 'batch_no', 'shade', 'calibre', name=op.f('uq_batches_product_id_batch_no_shade_calibre'))
    )
    op.create_index(op.f('ix_batches_company_id'), 'batches', ['company_id'], unique=False)
    op.create_index(op.f('ix_batches_product_id'), 'batches', ['product_id'], unique=False)
    op.create_index(op.f('ix_batches_tenant_id'), 'batches', ['tenant_id'], unique=False)
    op.create_table('bills',
    sa.Column('party_id', sa.UUID(), nullable=False),
    sa.Column('ledger_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('bill_no', sa.String(length=40), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('doc_type', sa.String(length=40), nullable=True),
    sa.Column('doc_id', sa.UUID(), nullable=True),
    sa.Column('voucher_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_bills_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], name=op.f('fk_bills_ledger_id_ledgers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_bills_party_id_parties'), use_alter=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_bills_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], name=op.f('fk_bills_voucher_id_vouchers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bills'))
    )
    op.create_index(op.f('ix_bills_company_id'), 'bills', ['company_id'], unique=False)
    op.create_index(op.f('ix_bills_doc_id'), 'bills', ['doc_id'], unique=False)
    op.create_index(op.f('ix_bills_ledger_id'), 'bills', ['ledger_id'], unique=False)
    op.create_index(op.f('ix_bills_party_id'), 'bills', ['party_id'], unique=False)
    op.create_index(op.f('ix_bills_tenant_id'), 'bills', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_bills_voucher_id'), 'bills', ['voucher_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_refresh_tokens_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_tenant_id'), 'refresh_tokens', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('sample_issues',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('party_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('issued_on', sa.Date(), nullable=False),
    sa.Column('expected_return_on', sa.Date(), nullable=True),
    sa.Column('returned_on', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_sample_issues_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_sample_issues_party_id_parties'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_sample_issues_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_sample_issues_project_id_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_sample_issues_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sample_issues'))
    )
    op.create_index(op.f('ix_sample_issues_company_id'), 'sample_issues', ['company_id'], unique=False)
    op.create_index(op.f('ix_sample_issues_party_id'), 'sample_issues', ['party_id'], unique=False)
    op.create_index(op.f('ix_sample_issues_product_id'), 'sample_issues', ['product_id'], unique=False)
    op.create_index(op.f('ix_sample_issues_project_id'), 'sample_issues', ['project_id'], unique=False)
    op.create_index(op.f('ix_sample_issues_tenant_id'), 'sample_issues', ['tenant_id'], unique=False)
    op.create_table('stock_journals',
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('journal_type', sa.String(length=20), nullable=False),
    sa.Column('doc_no', sa.String(length=40), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('from_godown_id', sa.UUID(), nullable=True),
    sa.Column('to_godown_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('lines', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('voucher_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_stock_journals_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_stock_journals_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_godown_id'], ['godowns.id'], name=op.f('fk_stock_journals_from_godown_id_godowns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_stock_journals_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_godown_id'], ['godowns.id'], name=op.f('fk_stock_journals_to_godown_id_godowns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], name=op.f('fk_stock_journals_voucher_id_vouchers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_journals')),
    sa.UniqueConstraint('company_id', 'journal_type', 'doc_no', name=op.f('uq_stock_journals_company_id_journal_type_doc_no'))
    )
    op.create_index(op.f('ix_stock_journals_branch_id'), 'stock_journals', ['branch_id'], unique=False)
    op.create_index(op.f('ix_stock_journals_company_id'), 'stock_journals', ['company_id'], unique=False)
    op.create_index(op.f('ix_stock_journals_from_godown_id'), 'stock_journals', ['from_godown_id'], unique=False)
    op.create_index(op.f('ix_stock_journals_tenant_id'), 'stock_journals', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_stock_journals_to_godown_id'), 'stock_journals', ['to_godown_id'], unique=False)
    op.create_index(op.f('ix_stock_journals_voucher_id'), 'stock_journals', ['voucher_id'], unique=False)
    op.create_table('trade_documents',
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('doc_type', sa.String(length=30), nullable=False),
    sa.Column('doc_no', sa.String(length=40), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('valid_till', sa.Date(), nullable=True),
    sa.Column('party_id', sa.UUID(), nullable=False),
    sa.Column('party_name', sa.String(length=200), nullable=False),
    sa.Column('party_gstin', sa.String(length=15), nullable=True),
    sa.Column('party_state_code', sa.String(length=2), nullable=False),
    sa.Column('place_of_supply', sa.String(length=2), nullable=False),
    sa.Column('is_interstate', sa.Boolean(), nullable=False),
    sa.Column('godown_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('reference_doc_id', sa.UUID(), nullable=True),
    sa.Column('supplier_ref_no', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('taxable_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cgst_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('sgst_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('igst_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('round_off', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payment_ledger_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('salesman', sa.String(length=100), nullable=True),
    sa.Column('transporter', sa.String(length=100), nullable=True),
    sa.Column('vehicle_no', sa.String(length=20), nullable=True),
    sa.Column('eway_bill_no', sa.String(length=20), nullable=True),
    sa.Column('irn', sa.String(length=80), nullable=True),
    sa.Column('voucher_id', sa.UUID(), nullable=True),
    sa.Column('cogs_voucher_id', sa.UUID(), nullable=True),
    sa.Column('receipt_voucher_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_trade_documents_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cogs_voucher_id'], ['vouchers.id'], name=op.f('fk_trade_documents_cogs_voucher_id_vouchers')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_trade_documents_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['godown_id'], ['godowns.id'], name=op.f('fk_trade_documents_godown_id_godowns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_trade_documents_party_id_parties'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_ledger_id'], ['ledgers.id'], name=op.f('fk_trade_documents_payment_ledger_id_ledgers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_trade_documents_project_id_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receipt_voucher_id'], ['vouchers.id'], name=op.f('fk_trade_documents_receipt_voucher_id_vouchers')),
    sa.ForeignKeyConstraint(['reference_doc_id'], ['trade_documents.id'], name=op.f('fk_trade_documents_reference_doc_id_trade_documents')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_trade_documents_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], name=op.f('fk_trade_documents_voucher_id_vouchers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trade_documents')),
    sa.UniqueConstraint('company_id', 'doc_type', 'doc_no', name=op.f('uq_trade_documents_company_id_doc_type_doc_no')),
    sa.UniqueConstraint('company_id', 'idempotency_key', name=op.f('uq_trade_documents_company_id_idempotency_key'))
    )
    op.create_index(op.f('ix_trade_documents_branch_id'), 'trade_documents', ['branch_id'], unique=False)
    op.create_index(op.f('ix_trade_documents_company_id'), 'trade_documents', ['company_id'], unique=False)
    op.create_index(op.f('ix_trade_documents_date'), 'trade_documents', ['date'], unique=False)
    op.create_index(op.f('ix_trade_documents_doc_type'), 'trade_documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_trade_documents_godown_id'), 'trade_documents', ['godown_id'], unique=False)
    op.create_index(op.f('ix_trade_documents_party_id'), 'trade_documents', ['party_id'], unique=False)
    op.create_index(op.f('ix_trade_documents_payment_ledger_id'), 'trade_documents', ['payment_ledger_id'], unique=False)
    op.create_index(op.f('ix_trade_documents_project_id'), 'trade_documents', ['project_id'], unique=False)
    op.create_index(op.f('ix_trade_documents_status'), 'trade_documents', ['status'], unique=False)
    op.create_index(op.f('ix_trade_documents_tenant_id'), 'trade_documents', ['tenant_id'], unique=False)
    op.create_table('voucher_lines',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('voucher_id', sa.UUID(), nullable=False),
    sa.Column('ledger_id', sa.UUID(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('narration', sa.String(length=500), nullable=True),
    sa.Column('cost_centre', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], name=op.f('fk_voucher_lines_ledger_id_ledgers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_voucher_lines_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], name=op.f('fk_voucher_lines_voucher_id_vouchers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voucher_lines'))
    )
    op.create_index(op.f('ix_voucher_lines_ledger_id'), 'voucher_lines', ['ledger_id'], unique=False)
    op.create_index(op.f('ix_voucher_lines_tenant_id'), 'voucher_lines', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_voucher_lines_voucher_id'), 'voucher_lines', ['voucher_id'], unique=False)
    op.create_table('bill_settlements',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('voucher_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('fk_bill_settlements_bill_id_bills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_bill_settlements_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], name=op.f('fk_bill_settlements_voucher_id_vouchers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bill_settlements'))
    )
    op.create_index(op.f('ix_bill_settlements_bill_id'), 'bill_settlements', ['bill_id'], unique=False)
    op.create_index(op.f('ix_bill_settlements_tenant_id'), 'bill_settlements', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_bill_settlements_voucher_id'), 'bill_settlements', ['voucher_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('godown_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('movement_type', sa.String(length=30), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('doc_type', sa.String(length=40), nullable=True),
    sa.Column('doc_id', sa.UUID(), nullable=True),
    sa.Column('narration', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_stock_movements_batch_id_batches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_stock_movements_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_stock_movements_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['godown_id'], ['godowns.id'], name=op.f('fk_stock_movements_godown_id_godowns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_movements_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_stock_movements_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_movements'))
    )
    op.create_index(op.f('ix_stock_movements_batch_id'), 'stock_movements', ['batch_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_branch_id'), 'stock_movements', ['branch_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_company_id'), 'stock_movements', ['company_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_date'), 'stock_movements', ['date'], unique=False)
    op.create_index(op.f('ix_stock_movements_doc_id'), 'stock_movements', ['doc_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_godown_id'), 'stock_movements', ['godown_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_product_id'), 'stock_movements', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_tenant_id'), 'stock_movements', ['tenant_id'], unique=False)
    op.create_table('stock_reservations',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('godown_id', sa.UUID(), nullable=False),
    sa.Column('party_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_stock_reservations_batch_id_batches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_stock_reservations_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['godown_id'], ['godowns.id'], name=op.f('fk_stock_reservations_godown_id_godowns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_stock_reservations_party_id_parties'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_reservations_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_stock_reservations_project_id_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_stock_reservations_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_reservations'))
    )
    op.create_index(op.f('ix_stock_reservations_batch_id'), 'stock_reservations', ['batch_id'], unique=False)
    op.create_index(op.f('ix_stock_reservations_company_id'), 'stock_reservations', ['company_id'], unique=False)
    op.create_index(op.f('ix_stock_reservations_godown_id'), 'stock_reservations', ['godown_id'], unique=False)
    op.create_index(op.f('ix_stock_reservations_party_id'), 'stock_reservations', ['party_id'], unique=False)
    op.create_index(op.f('ix_stock_reservations_product_id'), 'stock_reservations', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_reservations_project_id'), 'stock_reservations', ['project_id'], unique=False)
    op.create_index(op.f('ix_stock_reservations_tenant_id'), 'stock_reservations', ['tenant_id'], unique=False)
    op.create_table('trade_lines',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('hsn_code', sa.String(length=10), nullable=True),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('godown_id', sa.UUID(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_symbol', sa.String(length=12), nullable=False),
    sa.Column('area_sqft', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('rate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=7, scale=3), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=7, scale=3), nullable=False),
    sa.Column('cgst', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('sgst', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('igst', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cost_rate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_trade_lines_batch_id_batches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_id'], ['trade_documents.id'], name=op.f('fk_trade_lines_document_id_trade_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['godown_id'], ['godowns.id'], name=op.f('fk_trade_lines_godown_id_godowns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_trade_lines_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_trade_lines_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trade_lines'))
    )
    op.create_index(op.f('ix_trade_lines_batch_id'), 'trade_lines', ['batch_id'], unique=False)
    op.create_index(op.f('ix_trade_lines_document_id'), 'trade_lines', ['document_id'], unique=False)
    op.create_index(op.f('ix_trade_lines_godown_id'), 'trade_lines', ['godown_id'], unique=False)
    op.create_index(op.f('ix_trade_lines_product_id'), 'trade_lines', ['product_id'], unique=False)
    op.create_index(op.f('ix_trade_lines_tenant_id'), 'trade_lines', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_lines_tenant_id'), table_name='trade_lines')
    op.drop_index(op.f('ix_trade_lines_product_id'), table_name='trade_lines')
    op.drop_index(op.f('ix_trade_lines_godown_id'), table_name='trade_lines')
    op.drop_index(op.f('ix_trade_lines_document_id'), table_name='trade_lines')
    op.drop_index(op.f('ix_trade_lines_batch_id'), table_name='trade_lines')
    op.drop_table('trade_lines')
    op.drop_index(op.f('ix_stock_reservations_tenant_id'), table_name='stock_reservations')
    op.drop_index(op.f('ix_stock_reservations_project_id'), table_name='stock_reservations')
    op.drop_index(op.f('ix_stock_reservations_product_id'), table_name='stock_reservations')
    op.drop_index(op.f('ix_stock_reservations_party_id'), table_name='stock_reservations')
    op.drop_index(op.f('ix_stock_reservations_godown_id'), table_name='stock_reservations')
    op.drop_index(op.f('ix_stock_reservations_company_id'), table_name='stock_reservations')
    op.drop_index(op.f('ix_stock_reservations_batch_id'), table_name='stock_reservations')
    op.drop_table('stock_reservations')
    op.drop_index(op.f('ix_stock_movements_tenant_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_product_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_godown_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_doc_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_date'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_company_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_branch_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_batch_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_bill_settlements_voucher_id'), table_name='bill_settlements')
    op.drop_index(op.f('ix_bill_settlements_tenant_id'), table_name='bill_settlements')
    op.drop_index(op.f('ix_bill_settlements_bill_id'), table_name='bill_settlements')
    op.drop_table('bill_settlements')
    op.drop_index(op.f('ix_voucher_lines_voucher_id'), table_name='voucher_lines')
    op.drop_index(op.f('ix_voucher_lines_tenant_id'), table_name='voucher_lines')
    op.drop_index(op.f('ix_voucher_lines_ledger_id'), table_name='voucher_lines')
    op.drop_table('voucher_lines')
    op.drop_index(op.f('ix_trade_documents_tenant_id'), table_name='trade_documents')
    op.drop_index(op.f('ix_trade_documents_status'), table_name='trade_documents')
    op.drop_index(op.f('ix_trade_documents_project_id'), table_name='trade_documents')
    op.drop_index(op.f('ix_trade_documents_payment_ledger_id'), table_name='trade_documents')
    op.drop_index(op.f('ix_trade_documents_party_id'), table_name='trade_documents')
    op.drop_index(op.f('ix_trade_documents_godown_id'), table_name='trade_documents')
    op.drop_index(op.f('ix_trade_documents_doc_type'), table_name='trade_documents')
    op.drop_index(op.f('ix_trade_documents_date'), table_name='trade_documents')
    op.drop_index(op.f('ix_trade_documents_company_id'), table_name='trade_documents')
    op.drop_index(op.f('ix_trade_documents_branch_id'), table_name='trade_documents')
    op.drop_table('trade_documents')
    op.drop_index(op.f('ix_stock_journals_voucher_id'), table_name='stock_journals')
    op.drop_index(op.f('ix_stock_journals_to_godown_id'), table_name='stock_journals')
    op.drop_index(op.f('ix_stock_journals_tenant_id'), table_name='stock_journals')
    op.drop_index(op.f('ix_stock_journals_from_godown_id'), table_name='stock_journals')
    op.drop_index(op.f('ix_stock_journals_company_id'), table_name='stock_journals')
    op.drop_index(op.f('ix_stock_journals_branch_id'), table_name='stock_journals')
    op.drop_table('stock_journals')
    op.drop_index(op.f('ix_sample_issues_tenant_id'), table_name='sample_issues')
    op.drop_index(op.f('ix_sample_issues_project_id'), table_name='sample_issues')
    op.drop_index(op.f('ix_sample_issues_product_id'), table_name='sample_issues')
    op.drop_index(op.f('ix_sample_issues_party_id'), table_name='sample_issues')
    op.drop_index(op.f('ix_sample_issues_company_id'), table_name='sample_issues')
    op.drop_table('sample_issues')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_tenant_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_bills_voucher_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_tenant_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_party_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_ledger_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_doc_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_company_id'), table_name='bills')
    op.drop_table('bills')
    op.drop_index(op.f('ix_batches_tenant_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_product_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_company_id'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_whatsapp_messages_tenant_id'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_party_id'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_doc_id'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_company_id'), table_name='whatsapp_messages')
    op.drop_table('whatsapp_messages')
    op.drop_index(op.f('ix_vouchers_voucher_type'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_tenant_id'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_reference_id'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_fiscal_year_id'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_date'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_company_id'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_branch_id'), table_name='vouchers')
    op.drop_table('vouchers')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_tenant_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_party_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_company_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_index(op.f('ix_products_stock_unit_id'), table_name='products')
    op.drop_index('ix_products_company_name', table_name='products')
    op.drop_index(op.f('ix_products_company_id'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_brand_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_number_sequences_tenant_id'), table_name='number_sequences')
    op.drop_index(op.f('ix_number_sequences_fiscal_year_id'), table_name='number_sequences')
    op.drop_index(op.f('ix_number_sequences_company_id'), table_name='number_sequences')
    op.drop_table('number_sequences')
    op.drop_index(op.f('ix_ledgers_tenant_id'), table_name='ledgers')
    op.drop_index(op.f('ix_ledgers_group_id'), table_name='ledgers')
    op.drop_index('ix_ledgers_company_system_key', table_name='ledgers')
    op.drop_index(op.f('ix_ledgers_company_id'), table_name='ledgers')
    op.drop_table('ledgers')
    op.drop_index(op.f('ix_godowns_tenant_id'), table_name='godowns')
    op.drop_index(op.f('ix_godowns_company_id'), table_name='godowns')
    op.drop_index(op.f('ix_godowns_branch_id'), table_name='godowns')
    op.drop_table('godowns')
    op.drop_index(op.f('ix_units_tenant_id'), table_name='units')
    op.drop_index(op.f('ix_units_company_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_settings_tenant_id'), table_name='settings')
    op.drop_index(op.f('ix_settings_company_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_parties_tenant_id'), table_name='parties')
    op.drop_index('ix_parties_company_name', table_name='parties')
    op.drop_index(op.f('ix_parties_company_id'), table_name='parties')
    op.drop_table('parties')
    op.drop_index(op.f('ix_fiscal_years_tenant_id'), table_name='fiscal_years')
    op.drop_index(op.f('ix_fiscal_years_company_id'), table_name='fiscal_years')
    op.drop_table('fiscal_years')
    op.drop_index(op.f('ix_categories_tenant_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_company_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_brands_tenant_id'), table_name='brands')
    op.drop_index(op.f('ix_brands_company_id'), table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_branches_tenant_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_company_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_account_groups_tenant_id'), table_name='account_groups')
    op.drop_index(op.f('ix_account_groups_company_id'), table_name='account_groups')
    op.drop_table('account_groups')
    op.drop_index(op.f('ix_sync_outbox_tenant_id'), table_name='sync_outbox')
    op.drop_index(op.f('ix_sync_outbox_company_id'), table_name='sync_outbox')
    op.drop_table('sync_outbox')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_companies_tenant_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_company_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('tenants')
    # ### end Alembic commands ###
